# Generated by Django 5.1.5 on 2025-02-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=17)),
                ('slug', models.CharField(blank=True, max_length=26, null=True)),
                ('province_id', models.IntegerField()),
            ],
            options={
                'db_table': 'cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=19)),
                ('slug', models.CharField(max_length=17)),
                ('tel_prefix', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'provinces',
                'managed': False,
            },
        ),
    ]
