# Generated by Django 5.1.5 on 2025-02-20 05:25

import core.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('core', '0001_initial'),
        ('employer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerFilterMixin',
            fields=[
                ('locationfiltermixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.locationfiltermixin')),
            ],
            bases=(core.mixins.GenderFilterMixin, 'core.locationfiltermixin', core.mixins.CreationTimeFilterMixin),
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')])),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('birthday', models.DateField()),
                ('city', models.ForeignKey(default=301, on_delete=django.db.models.deletion.CASCADE, related_name='city_jobseekers', to='account.cities')),
                ('province', models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='state_jobseekers', to='account.provinces')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('rejected', 'Rejected'), ('seen', 'Seen'), ('interview', 'Interview'), ('accepted', 'Accepted')], default='sent')),
                ('description', models.TextField(blank=True, null=True)),
                ('job_opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_applications', to='employer.jobopportunity')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_applications', to='job_seeker.jobseeker')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.TextField()),
                ('score', models.TextField(default=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='job_seeker.question')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=50)),
                ('kind', models.CharField(choices=[('psychology', 'Psychology'), ('questionnaire', 'Questionnaire')])),
                ('publish', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', models.JSONField(default=dict, null=True)),
                ('experience', models.IntegerField()),
                ('education', models.CharField(choices=[('under_diploma', 'Under Diploma'), ('bachelor', 'Bachelor'), ('diploma', 'Diploma'), ('master', 'Master'), ('phd', 'Phd')])),
                ('stack', models.CharField(choices=[('front_end', 'Front End'), ('back_end', 'Back End'), ('full_stack', 'Full Stack'), ('wordpress', 'Wordpress'), ('graphic_designer', 'Graphic Designer'), ('seo', 'Seo')])),
                ('job_seeker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job_seeker.jobseeker')),
                ('test', models.ManyToManyField(related_name='resume', to='job_seeker.test')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='job_seeker.test'),
        ),
    ]
