# Generated by Django 5.1.5 on 2025-02-23 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0002_alter_jobseeker_city_alter_jobseeker_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='birthday',
        ),
    ]
