# Generated by Django 5.1.5 on 2025-02-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0003_remove_jobseeker_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='bio',
            field=models.TextField(blank=True, help_text='a brief text about the job seeker', null=True),
        ),
    ]
