# Generated by Django 5.1.5 on 2025-02-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0004_alter_jobseeker_bio'),
        ('manager', '0004_technologycategory_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.CharField(choices=[('intern', 'Intern'), ('junior', 'Junior'), ('midlevel', 'Midlevel'), ('senior', 'Senior'), ('lead', 'Lead')]),
        ),
        migrations.RemoveField(
            model_name='resume',
            name='stack',
        ),
        migrations.AddField(
            model_name='resume',
            name='stack',
            field=models.ManyToManyField(related_name='resume', to='manager.technologycategory'),
        ),
    ]
