# Generated by Django 5.1.5 on 2025-04-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0005_alter_resume_experience_remove_resume_stack_and_more'),
        ('manager', '0004_technologycategory_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='stack',
            field=models.ManyToManyField(blank=True, null=True, related_name='resume', to='manager.technologycategory'),
        ),
    ]
