# Generated by Django 5.1.5 on 2025-04-21 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0006_alter_resume_stack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='banned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banned_jobseekers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='banned_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='is_banned',
            field=models.BooleanField(default=True),
        ),
    ]
