# Generated by Django 5.1.5 on 2025-02-23 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('employer', '0003_remove_employer_gender_alter_employer_city_and_more'),
        ('job_seeker', '0002_alter_jobseeker_city_alter_jobseeker_province'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cities',
        ),
        migrations.DeleteModel(
            name='Provinces',
        ),
    ]
