# Generated by Django 5.1.2 on 2024-11-23 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0001_initial'),
        ('job_seeker', '0001_initial'),
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employercartitems',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.package'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_opportunities', to='employer.employer'),
        ),
        migrations.AddField(
            model_name='viewedresume',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employer'),
        ),
        migrations.AddField(
            model_name='viewedresume',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker.resume'),
        ),
    ]
