# Generated by Django 5.1.2 on 2024-11-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopportunity',
            name='acitve',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='registered'),
        ),
    ]
