# Generated by Django 5.1.2 on 2024-11-20 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0001_initial'),
        ('job_seeker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewedresume',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker.resume'),
        ),
    ]
