# Generated by Django 5.1.2 on 2024-11-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_remove_employer_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobopportunity',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='employer',
            name='company_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='expire_at',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
