# Generated by Django 5.1.2 on 2024-11-23 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_initial'),
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employercart',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='employercartitems',
            name='price',
        ),
        migrations.RemoveField(
            model_name='employercartitems',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='employercartitems',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='employer.employercart'),
        ),
        migrations.CreateModel(
            name='EmployerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.DecimalField(decimal_places=3, max_digits=10)),
                ('order_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='employer.employer')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='employer.employerorder')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.package')),
            ],
        ),
    ]
