# Generated by Django 5.1.3 on 2024-12-12 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('employer', '0002_initial'),
        ('job_seeker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewschedule',
            name='apply',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='job_seeker.application'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='account.cities'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='account.countries'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_opportunities', to='employer.employer'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_states', to='account.states'),
        ),
        migrations.AddField(
            model_name='viewedappliedresume',
            name='job_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.jobopportunity'),
        ),
        migrations.AddField(
            model_name='viewedappliedresume',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker.resume'),
        ),
        migrations.AddField(
            model_name='viewedresume',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employer'),
        ),
        migrations.AddField(
            model_name='viewedresume',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker.resume'),
        ),
    ]
