# Generated by Django 5.1.3 on 2024-11-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerorder',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending'),
        ),
    ]
