# Generated by Django 5.1.2 on 2024-11-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_jobopportunity_acitve_jobopportunity_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobopportunity',
            name='acitve',
        ),
    ]
