# Generated by Django 5.1.2 on 2024-11-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_rename_name_jobopportunity_title_and_more'),
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='package',
            field=models.ManyToManyField(related_name='packages', to='package.package'),
        ),
    ]
