# Generated by Django 5.1.2 on 2024-11-18 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_remove_jobopportunity_acitve'),
        ('job_seeker', '0003_alter_resume_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employer')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker.resume')),
            ],
        ),
    ]
