# Generated by Django 5.1.2 on 2024-11-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_remove_employercart_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employercart',
            name='is_paid',
        ),
    ]
