# Generated by Django 5.1.3 on 2024-11-30 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_alter_jobopportunity_expire_at'),
        ('job_seeker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_seeker_time', models.DateTimeField(blank=True, null=True)),
                ('employer_time', models.DateTimeField(blank=True, null=True)),
                ('interview_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('conflict', 'Conflict')], default='pending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='job_seeker.application')),
            ],
        ),
    ]
