# Generated by Django 5.1.2 on 2024-11-13 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_employer_package'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='job_opportunity',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='package',
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='employer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='employers', to='employer.employer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
