# Generated by Django 5.1.3 on 2024-11-30 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_interviewschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewschedule',
            old_name='job_apply',
            new_name='apply',
        ),
    ]
