# Generated by Django 5.1.2 on 2024-11-20 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_viewedresume'),
        ('package', '0008_alter_package_price_alter_purchasedpackage_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='employer.employer')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerBasketItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.package')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='employer.employercart')),
            ],
        ),
    ]
