# Generated by Django 5.1.2 on 2024-11-23 06:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_remove_employercart_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employercart',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employerorder',
            name='employer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='employer.employer'),
        ),
    ]
