# Generated by Django 5.1.2 on 2024-11-23 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_employercart_added_at_alter_employerorder_employer'),
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployerCartItems',
            new_name='EmployerCartItem',
        ),
    ]
