# Generated by Django 5.1.2 on 2024-11-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_remove_employer_job_opportunity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='company_name',
            new_name='city',
        ),
        migrations.AddField(
            model_name='employer',
            name='address',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='id_number',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='postal_code',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
    ]
