# Generated by Django 5.1.3 on 2024-12-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_rename_job_apply_interviewschedule_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewschedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected_by_employer', 'Rejected By Employer'), ('rejected_by_jobseeker', 'Rejected By Jobseeker'), ('conflict', 'Conflict')], default='pending'),
        ),
    ]
