# Generated by Django 5.1.2 on 2024-11-13 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_rename_company_name_employer_city_employer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopportunity',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_opportunities', to='employer.employer'),
        ),
        migrations.AlterField(
            model_name='jobopportunity',
            name='expire_at',
            field=models.DateField(),
        ),
    ]
