# Generated by Django 5.1.2 on 2024-11-23 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_rename_employercartitems_employercartitem'),
        ('payment', '0002_alter_payment_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerorder',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='employer.employer'),
        ),
        migrations.AlterField(
            model_name='employerorder',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='payment.payment'),
        ),
    ]
