# Generated by Django 5.1.2 on 2024-12-07 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_cities_countries_regions_states_subregions_and_more'),
        ('employer', '0007_alter_interviewschedule_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='employers', to='account.countries'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='account.cities'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='account.countries'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employers', to='account.cities'),
        ),
    ]
