# Generated by Django 5.1.2 on 2024-11-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_alter_employerorder_employer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerorder',
            name='order_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
