# Generated by Django 5.1.3 on 2024-12-07 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_cities_countries_regions_states_subregions_and_more'),
        ('employer', '0008_employer_country_jobopportunity_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='state_employers', to='account.states'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='job_states', to='account.states'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_emoployers', to='account.cities'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_employers', to='account.countries'),
        ),
    ]
