# Generated by Django 5.1.2 on 2024-11-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0008_alter_employer_user_alter_jobopportunity_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopportunity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
