# Generated by Django 5.1.3 on 2024-12-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_employer_state_jobopportunity_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], null=True),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], null=True),
        ),
    ]
