# Generated by Django 5.1.3 on 2024-12-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0010_employer_gender_jobopportunity_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')]),
        ),
        migrations.AlterField(
            model_name='jobopportunity',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')]),
        ),
    ]
