# Generated by Django 5.1.2 on 2024-12-09 07:01

import common.mixins
import django.db.models.deletion
import rest_framework.views
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('employer', '0011_alter_employer_gender_alter_jobopportunity_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterEmployerMixin',
            fields=[
                ('locationfiltermixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.locationfiltermixin')),
            ],
            bases=('common.locationfiltermixin', common.mixins.GenderFilterMixin),
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='name',
            new_name='title',
        ),
        migrations.CreateModel(
            name='AllEmployers',
            fields=[
                ('filteremployermixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employer.filteremployermixin')),
            ],
            bases=(rest_framework.views.APIView, 'employer.filteremployermixin'),
        ),
    ]
