# Generated by Django 5.1.3 on 2024-12-10 06:36

import common.mixins
import django.db.models.deletion
import employer.mixins
import rest_framework.views
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('employer', '0013_employer_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterJobOpportunityMixin',
            fields=[
                ('locationfiltermixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.locationfiltermixin')),
            ],
            bases=('common.locationfiltermixin', common.mixins.GenderFilterMixin, common.mixins.CreationTimeFilterMixin),
        ),
        migrations.CreateModel(
            name='AllJobOffers',
            fields=[
                ('filterjobopportunitymixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employer.filterjobopportunitymixin')),
            ],
            bases=(rest_framework.views.APIView, 'employer.filterjobopportunitymixin'),
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('filterjobopportunitymixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employer.filterjobopportunitymixin')),
            ],
            bases=(rest_framework.views.APIView, employer.mixins.CountryCityIdMixin, 'employer.filterjobopportunitymixin'),
        ),
    ]
