# Generated by Django 5.1.3 on 2024-12-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0014_filterjobopportunitymixin_alljoboffers_joboffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewedresume',
            name='seen_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
