# Generated by Django 5.1.3 on 2024-12-11 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0015_viewedresume_seen_at'),
        ('job_seeker', '0016_jobseekerfiltermixin_alljobseekers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewedAppliedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.jobopportunity')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker.resume')),
            ],
        ),
    ]
