# Generated by Django 5.1.2 on 2024-11-11 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='payment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='priority',
            field=models.IntegerField(choices=[(0, 'normal'), (1, 'urgent')], default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.IntegerField(choices=[(0, 'offer'), (1, 'resume')]),
        ),
    ]
