# Generated by Django 5.1.2 on 2024-11-13 04:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_package_payment_package_priority_package_remaining_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='employer',
            field=models.ManyToManyField(related_name='employers', to=settings.AUTH_USER_MODEL),
        ),
    ]
