# Generated by Django 5.1.2 on 2024-11-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_package_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedpackage',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
