# Generated by Django 5.1.2 on 2024-11-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_remove_package_employer_remove_package_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchasedpackage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
