# Generated by Django 5.1.2 on 2024-11-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_purchasedpackage_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedpackage',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='purchasedpackage',
            name='remaining',
            field=models.IntegerField(),
        ),
    ]
