# Generated by Django 5.1.2 on 2024-11-15 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_alter_package_price_alter_purchasedpackage_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedpackage',
            name='employer',
        ),
        migrations.AddField(
            model_name='purchasedpackage',
            name='employer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
