# Generated by Django 5.1.2 on 2024-11-17 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_purchasedpackage_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedpackage',
            name='count',
        ),
    ]
