# Generated by Django 5.1.2 on 2024-11-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0006_remove_purchasedpackage_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='count',
            field=models.IntegerField(),
        ),
    ]
