# Generated by Django 5.1.2 on 2024-11-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0007_alter_package_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchasedpackage',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
