# Generated by Django 5.1.5 on 2025-02-17 08:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=17)),
                ('slug', models.CharField(blank=True, max_length=26, null=True)),
                ('province_id', models.IntegerField()),
            ],
            options={
                'db_table': 'cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=19)),
                ('slug', models.CharField(max_length=17)),
                ('tel_prefix', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'provinces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09121314156'", regex='^\\d{11}$')])),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('send_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('email', 'Email'), ('sms', 'Sms')])),
                ('type', models.CharField(choices=[('otp', 'Otp'), ('login', 'Loign'), ('order', 'Order'), ('resume', 'Resume'), ('expire', 'Expire')])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('undelivered', 'Undelivered'), ('failed', 'Failed')], default='pending')),
                ('content', models.TextField(blank=True, null=True)),
                ('message_id', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, null=True, unique=True)),
                ('mobile', models.TextField(max_length=11, unique=True, verbose_name='mobile number')),
                ('mobile_code', models.CharField(default='+98', help_text='کد موبایل کاربر - DialCode', max_length=6)),
                ('role', models.SmallIntegerField(choices=[(0, 'pre_register'), (1, 'employer'), (2, 'job_seeker'), (3, 'operator'), (10, 'admin')], default=0, help_text='handling the user role')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(default='-', help_text='اسم کوچک ', max_length=100, null=True)),
                ('family_name', models.CharField(default='-', help_text='نام خانوادگی ', max_length=100, null=True)),
                ('personal_national_id', models.CharField(blank=True, help_text='شناسه ملی (حقیقی)', max_length=30, null=True)),
                ('phone', models.CharField(blank=True, help_text='شماره تلفن ثابت', max_length=30, null=True)),
                ('birthday', models.DateTimeField(blank=True, help_text='تاریخ تولد (حقیقی)', null=True)),
                ('banned', models.BooleanField(default=False, help_text='یوزر از سایت بن شده')),
                ('need_complete', models.BooleanField(default=True, help_text='جهت تشخیص نیاز به تکمیل پروفایل کاربری')),
                ('ban_cause', models.TextField(blank=True, help_text='علت بن شدن یوزر از سایت', null=True)),
                ('is_real', models.BooleanField(default=True, help_text='یوزر حقیقی\u200c است یا حقوقی')),
                ('gender', models.BooleanField(blank=True, help_text='male = True, female = False', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('banned_by', models.ForeignKey(blank=True, help_text='یوزر توسط چه کسی بن شده', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_banned_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100)),
                ('browser', models.CharField(blank=True, max_length=300, null=True)),
                ('os', models.CharField(blank=True, max_length=300, null=True)),
                ('device', models.CharField(blank=True, max_length=300, null=True)),
                ('for_admin', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('log_kind', models.SmallIntegerField(choices=[(0, 'ورود کاربر'), (1, 'رمز اشتباه'), (2, 'خروج کاربر'), (3, 'توکن اشتباه'), (4, 'در خواست فراموشی رمز عبور با پیامک'), (5, 'تغییر رمز عبور پس از فراموشی رمز عبور با پیامک')], default=0, help_text='نوع لاگ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
