# Generated by Django 5.1.2 on 2024-11-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='total_price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
