# Generated by Django 5.1.2 on 2024-11-17 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_status',
            new_name='status',
        ),
    ]
