# Generated by Django 5.1.2 on 2024-11-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='total_price',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='authority',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
