# Generated by Django 5.1.2 on 2024-11-11 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_package_remove_payment_user_payment_checkout_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Package',
        ),
    ]
