# Generated by Django 5.1.2 on 2024-11-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_rename_total_price_payment_amount_payment_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='authority',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
