# Generated by Django 5.1.2 on 2024-11-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_delete_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='employer',
        ),
        migrations.AddField(
            model_name='payment',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
    ]
