# Generated by Django 5.1.2 on 2024-11-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='id_number',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
