# Generated by Django 5.1.2 on 2024-11-24 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_payment_id_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='id_number',
            new_name='payment_id',
        ),
    ]
