# Generated by Django 5.1.2 on 2024-11-15 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_alter_jobopportunity_created_at'),
        ('payment', '0005_remove_payment_employer_payment_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='employer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employer.employer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='checkout_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
