# Generated by Django 5.1.5 on 2025-02-23 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='gender',
        ),
        migrations.AlterField(
            model_name='employer',
            name='city',
            field=models.ForeignKey(default=301, help_text='city of the company . default is Tehran', on_delete=django.db.models.deletion.CASCADE, related_name='city_emoployers', to='location.cities'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='id_number',
            field=models.CharField(help_text='company register number', max_length=25),
        ),
        migrations.AlterField(
            model_name='employer',
            name='province',
            field=models.ForeignKey(default=8, help_text='province of the company . default is Tehran', on_delete=django.db.models.deletion.CASCADE, related_name='state_employers', to='location.provinces'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='title',
            field=models.CharField(help_text='company name', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobopportunity',
            name='city',
            field=models.ForeignKey(default=301, help_text='city of the offer . default is Tehran', on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='location.cities'),
        ),
        migrations.AlterField(
            model_name='jobopportunity',
            name='province',
            field=models.ForeignKey(help_text='province of the offer . default is Tehran', on_delete=django.db.models.deletion.CASCADE, related_name='job_states', to='location.provinces'),
        ),
    ]
