# Generated by Django 5.1.5 on 2025-02-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_remove_employer_gender_alter_employer_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopportunity',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], default='unisex'),
        ),
    ]
