# Generated by Django 5.1.5 on 2025-02-24 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_alter_jobopportunity_gender'),
        ('manager', '0002_technologycategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopportunity',
            name='category',
            field=models.ManyToManyField(related_name='offers', to='manager.technologycategory'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='cooperation',
            field=models.CharField(choices=[('full_time', 'Fulltime'), ('part_time', 'Parttime'), ('project', 'Project')], default='full_time'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='experience',
            field=models.CharField(choices=[('intern', 'Intern'), ('junior', 'Junior'), ('midlevel', 'Midlevel'), ('senior', 'Senior'), ('lead', 'Lead')], default='junior'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='updated_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='work_mode',
            field=models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'Onsite')], default='onsite'),
        ),
    ]
