# Generated by Django 5.1.5 on 2025-02-24 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_jobopportunity_category_jobopportunity_cooperation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobopportunity',
            old_name='category',
            new_name='stack',
        ),
    ]
