# Generated by Django 5.1.5 on 2025-02-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_rename_category_jobopportunity_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='company_email',
            field=models.EmailField(default=None, max_length=512),
            preserve_default=False,
        ),
    ]
