# Generated by Django 5.1.5 on 2025-03-03 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_employer_company_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='title',
            new_name='company_name',
        ),
    ]
