# Generated by Django 5.1.5 on 2025-04-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_employer_banned_at_employer_banned_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
