# Generated by Django 5.1.5 on 2025-04-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0010_alter_employer_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopportunity',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
