# Generated by Django 5.1.5 on 2025-04-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0011_jobopportunity_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopportunity',
            name='stack_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
