# Generated by Django 5.1.5 on 2025-04-30 12:44

import django.db.models.deletion
import rest_framework.views
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0012_jobopportunity_stack_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOfferList',
            fields=[
                ('filterjobopportunitymixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employer.filterjobopportunitymixin')),
            ],
            bases=(rest_framework.views.APIView, 'employer.filterjobopportunitymixin'),
        ),
    ]
