# Generated by Django 5.1.5 on 2025-05-04 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0013_jobofferlist'),
        ('package', '0002_remove_purchasedpackage_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopportunity',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_job_opportunities', to='package.package'),
        ),
    ]
