# Generated by Django 5.1.2 on 2024-11-16 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'permissions': [('delete_the_resume', 'Can delete resume')]},
        ),
    ]
