# Generated by Django 5.1.2 on 2024-11-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('rejected', 'Rejected'), ('seen', 'Seen'), ('interview', 'Interview'), ('accepted', 'Accepted')], default='sent'),
        ),
    ]
