# Generated by Django 5.1.2 on 2024-11-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0002_remove_jobseeker_resume_jobseeker_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='birthday',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
