# Generated by Django 5.1.3 on 2024-12-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0002_test_questionandanswers_resume_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
