# Generated by Django 5.1.2 on 2024-11-17 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0002_alter_resume_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={},
        ),
    ]
