# Generated by Django 5.1.3 on 2024-12-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0003_test_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='count',
            field=models.IntegerField(default=10, max_length=100),
        ),
    ]
