# Generated by Django 5.1.2 on 2024-11-13 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0003_jobseeker_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='exprience',
            new_name='experience',
        ),
    ]
