# Generated by Django 5.1.2 on 2024-11-13 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0008_alter_employer_user_alter_jobopportunity_created_at'),
        ('job_seeker', '0005_alter_application_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job_opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.jobopportunity'),
        ),
    ]
