# Generated by Django 5.1.2 on 2024-11-13 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0008_alter_employer_user_alter_jobopportunity_created_at'),
        ('job_seeker', '0006_alter_application_job_opportunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job_opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_applications', to='employer.jobopportunity'),
        ),
        migrations.AlterField(
            model_name='application',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_applications', to='job_seeker.jobseeker'),
        ),
    ]
