# Generated by Django 5.1.3 on 2024-12-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0006_alter_questionandanswers_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionandanswers',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
