# Generated by Django 5.1.3 on 2024-12-04 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0008_questionandanswers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='stack',
            field=models.CharField(choices=[('front_end', 'Front End'), ('back_end', 'Back End'), ('full_stack', 'Full Stack'), ('wordpress', 'Wordpress'), ('graphic_designer', 'Graphic Designer'), ('seo', 'Seo')], default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.CharField(choices=[('under_diploma', 'Under Diploma'), ('bachelor', 'Bachelor'), ('diploma', 'Diploma'), ('master', 'Master'), ('phd', 'Phd')]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='job_seeker.jobseeker'),
        ),
    ]
