# Generated by Django 5.1.3 on 2024-12-05 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0008_questionandanswers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='job_seeker.jobseeker'),
        ),
    ]
