# Generated by Django 5.1.3 on 2024-12-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0009_resume_stack_alter_resume_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
