# Generated by Django 5.1.2 on 2024-12-07 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0009_alter_resume_job_seeker'),
        ('job_seeker', '0010_alter_resume_skills'),
    ]

    operations = [
    ]
