# Generated by Django 5.1.2 on 2024-12-07 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_cities_countries_regions_states_subregions_and_more'),
        ('job_seeker', '0011_merge_20241207_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='jobseekers', to='account.cities'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='jobseekers', to='account.countries'),
            preserve_default=False,
        ),
    ]
