# Generated by Django 5.1.3 on 2024-12-07 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_cities_countries_regions_states_subregions_and_more'),
        ('job_seeker', '0012_jobseeker_city_jobseeker_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='state_jobseekers', to='account.states'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_jobseekers', to='account.cities'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_jobseekers', to='account.countries'),
        ),
    ]
