# Generated by Django 5.1.3 on 2024-12-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0014_jobseeker_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')]),
        ),
    ]
