# Generated by Django 5.1.2 on 2024-12-09 07:01

import common.mixins
import django.db.models.deletion
import rest_framework.views
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('job_seeker', '0015_alter_jobseeker_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerFilterMixin',
            fields=[
                ('locationfiltermixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.locationfiltermixin')),
            ],
            bases=(common.mixins.GenderFilterMixin, 'common.locationfiltermixin'),
        ),
        migrations.CreateModel(
            name='AllJobSeekers',
            fields=[
                ('jobseekerfiltermixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='job_seeker.jobseekerfiltermixin')),
            ],
            bases=(rest_framework.views.APIView, 'job_seeker.jobseekerfiltermixin'),
        ),
    ]
