# Generated by Django 5.1.3 on 2024-12-11 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0016_jobseekerfiltermixin_alljobseekers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='job_seeker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job_seeker.jobseeker'),
        ),
    ]
