# Generated by Django 5.1.3 on 2024-12-12 18:19

import common.mixins
import django.db.models.deletion
import employer.mixins
import rest_framework.views
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterEmployerMixin',
            fields=[
                ('locationfiltermixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.locationfiltermixin')),
            ],
            bases=('common.locationfiltermixin', common.mixins.GenderFilterMixin, common.mixins.CreationTimeFilterMixin),
        ),
        migrations.CreateModel(
            name='FilterJobOpportunityMixin',
            fields=[
                ('locationfiltermixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.locationfiltermixin')),
            ],
            bases=('common.locationfiltermixin', common.mixins.GenderFilterMixin, common.mixins.CreationTimeFilterMixin),
        ),
        migrations.CreateModel(
            name='EmployerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending')),
                ('order_at', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployerOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_seeker_time', models.DateTimeField(blank=True, null=True)),
                ('employer_time', models.DateTimeField(blank=True, null=True)),
                ('interview_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected_by_employer', 'Rejected By Employer'), ('rejected_by_jobseeker', 'Rejected By Jobseeker'), ('conflict', 'Conflict')], default='pending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')])),
                ('active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('approved', 'Approved'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='registered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expire_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ViewedAppliedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViewedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllEmployers',
            fields=[
                ('filteremployermixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employer.filteremployermixin')),
            ],
            bases=(rest_framework.views.APIView, 'employer.filteremployermixin'),
        ),
        migrations.CreateModel(
            name='AllJobOffers',
            fields=[
                ('filterjobopportunitymixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employer.filterjobopportunitymixin')),
            ],
            bases=(rest_framework.views.APIView, 'employer.filterjobopportunitymixin'),
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('filterjobopportunitymixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employer.filterjobopportunitymixin')),
            ],
            bases=(rest_framework.views.APIView, employer.mixins.CountryCityIdMixin, 'employer.filterjobopportunitymixin'),
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')])),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('id_number', models.CharField(max_length=25)),
                ('postal_code', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_emoployers', to='account.cities')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_employers', to='account.countries')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_employers', to='account.states')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployerCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='employer.employer')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='employer.employercart')),
            ],
        ),
    ]
