# Generated by Django 5.1.5 on 2025-02-16 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('employer', '0001_initial'),
        ('job_seeker', '0001_initial'),
        ('package', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employercartitem',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.package'),
        ),
        migrations.AddField(
            model_name='employerorder',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='employer.employer'),
        ),
        migrations.AddField(
            model_name='employerorder',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='payment.payment'),
        ),
        migrations.AddField(
            model_name='employerorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='employer.employerorder'),
        ),
        migrations.AddField(
            model_name='employerorderitem',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='package.package'),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='apply',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='job_seeker.application'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='city',
            field=models.ForeignKey(default=301, on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='account.cities'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_opportunities', to='employer.employer'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='province',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='job_states', to='account.provinces'),
        ),
        migrations.AddField(
            model_name='viewedappliedresume',
            name='job_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.jobopportunity'),
        ),
        migrations.AddField(
            model_name='viewedappliedresume',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker.resume'),
        ),
        migrations.AddField(
            model_name='viewedresume',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employer'),
        ),
        migrations.AddField(
            model_name='viewedresume',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker.resume'),
        ),
    ]
