# Generated by Django 5.1.5 on 2025-02-16 10:10

import django.db.models.deletion
import rest_framework.views
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0001_initial'),
        ('job_seeker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllEmployers',
            fields=[
                ('filteremployermixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employer.filteremployermixin')),
            ],
            bases=(rest_framework.views.APIView, 'employer.filteremployermixin'),
        ),
        migrations.CreateModel(
            name='AllJobSeekers',
            fields=[
                ('jobseekerfiltermixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='job_seeker.jobseekerfiltermixin')),
            ],
            bases=(rest_framework.views.APIView, 'job_seeker.jobseekerfiltermixin'),
        ),
    ]
