# Generated by Django 5.1.5 on 2025-02-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_technologycategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologycategory',
            name='name',
            field=models.CharField(db_index=True, max_length=250, unique=True),
        ),
    ]
