# Generated by Django 5.1.5 on 2025-02-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_technologycategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologycategory',
            name='deleted',
            field=models.BooleanField(default=False, help_text='virtual delete'),
        ),
    ]
