# Generated by Django 5.1.5 on 2025-04-14 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_technologycategory_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologycategory',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='technologycategory',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='technologycategory',
            name='deleted_by',
        ),
    ]
