# Generated by Django 5.1.5 on 2025-04-21 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_employer_banned_at_employer_banned_by_and_more'),
        ('job_seeker', '0007_jobseeker_banned_at_jobseeker_banned_by_and_more'),
        ('manager', '0005_remove_technologycategory_deleted_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllEmployers',
            new_name='EmployersMng',
        ),
        migrations.RenameModel(
            old_name='AllJobSeekers',
            new_name='JobSeekersMng',
        ),
    ]
