# Generated by Django 5.1.3 on 2024-11-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('otp', 'Otp'), ('login', 'Loign'), ('order', 'Order'), ('resume', 'Resume')]),
        ),
    ]
