# Generated by Django 5.1.3 on 2024-11-25 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09121314156'", regex='^\\d{11}$')])),
                ('send_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('otp', 'Otp'), ('login', 'Loign'), ('order', 'Order')])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('undelivered', 'Undelivered'), ('failed', 'Failed')], default='sent')),
                ('content', models.TextField(blank=True, null=True)),
                ('message_id', models.CharField(blank=True)),
            ],
        ),
    ]
