# Generated by Django 5.1.3 on 2024-11-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_options_alter_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('otp', 'Otp'), ('login', 'Loign'), ('order', 'Order'), ('resume', 'Resume'), ('expire', 'Expire')]),
        ),
    ]
